ENGLISH_ONSETS = set(['B',
        'B L',
        'B R',
        'B Y',
        'CH',
        'D',
        'D R',
        'DH',
        'F',
        'F L',
        'F R',
        'F Y',
        'G',
        'G L',
        'G R',
        'G W',
        'G Y',
        'HH',
        'HH Y',
        'JH',
        'K',
        'K L',
        'K R',
        'K W',
        'K Y',
        'L',
        'M',
        'M Y',
        'N',
        'P',
        'P L',
        'P R',
        'P Y',
        'R',
        'S',
        'S K',
        'S K L',
        'S K R',
        'S K W',
        'S K Y',
        'S L',
        'S M',
        'S N',
        'S P',
        'S P L',
        'S P R',
        'S P Y',
        'S T',
        'S T R',
        'S W',
        'SH',
        'SH R',
        'T',
        'T R',
        'T W',
        'TH',
        'TH R',
        'TH W',
        'V',
        'V Y',
        'W',
        'Y',
        'Z',
        'ZH'])

ENGLISH_VOWEL_PATTERN = r'[AEIUOaeiuo][HYWRAOEhywraoe]\d?'
